hytrip/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='index'),
    path('maps/', include('maps.urls'), name='maps'),
    path('post/', include('post.urls'), name='post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# django.contrib.auth.urls -> 장고에 기본적으로 내장된 인증 기능.

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
]

maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.default_map, name="default"),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),  # 조회
    path('<int:pk>/', views.post_detail, name='post_detail'),  # 디테일
    path('new/', views.post_new, name='post_new'),  # 작성
    path('edit/<int:pk>/', views.post_edit, name='post_edit'),  # 수정
    path('remove/<int:pk>/', views.post_remove, name='post_remove'), #삭제
    path('<int:pk>/comments/new/',views.post_comment, name='post_comment'), #댓글 작성
    # path('<int:pk>/comments/<int:pk>/edit', views.comment_edit, name='comment_edit'),  # 수정
    path('comments/remove/<int:pk>/', views.comment_remove, name='comment_remove'),  # 삭제
]

main/models.py
from django.db import models

# Create your models here.

maps/models.py
from django.db import models

# Create your models here.

post/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from pytz import timezone

def local_time(input_time):
    fmt = '%Y-%m-%d %H:%M'
    my_zone = timezone(settings.TIME_ZONE)
    my_local_time = input_time.astimezone(my_zone)
    return my_local_time.strftime(fmt)

class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,  # 'auth.User'라고 쓰는 것보다 강추
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='게시자',
    )
    name = models.CharField('제목', max_length=20)
    desc = models.TextField('내용')
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='tags')
    post_hit = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

    def short_content(self):
        if self.desc:
            t = self.desc[:20] + '...'   # content 속성의 일부만 반환
        else:
            t = '(내용 없음)'
        return t
    short_content.short_description = '간략 내용'

    def tagged(self):
        ts = self.tags.all()
        return  ', '.join(map(str, ts))

    tagged.short_description = '태그 집합'

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'

    def get_absolute_url(self):
        # return reverse('blog:post_detail', args=[self.pk])
        return reverse('post:post_detail', kwargs={'pk': self.pk})

    @property
    def update_counter(self):
        self.post_hit = self.post_hit + 1
        self.save()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments', verbose_name='게시물')
    message = models.TextField('댓글')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-post__id', '-id']  # '-post__id', '-id'

    def __str__(self):
        return self.message

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'

class Tag(models.Model):
    name = models.CharField('태그', max_length=100, unique=True)

    class Meta:
        ordering = ['-id']  # Tag 객체의 기본 정렬 순서 지정

    def __str__(self):
        return self.name

post/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('id', 'message')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'name', 'desc', 'photo', 'tags')

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

maps/views.py
from django.shortcuts import render

def default_map(request):
    # TODO: move this token to Django settings from an environment variable
    # found in the Mapbox account settings and getting started instructions
    # see https://www.mapbox.com/account/ under the "Access tokens" section
    mapbox_access_token = 'pk.my_mapbox_access_token'
    return render(request, 'maps/default.html',
                  {'mapbox_access_token':mapbox_access_token})

post/views.py
from email import message
from io import BytesIO
from PIL import Image, ImageFont, ImageDraw
from django.contrib.sites import requests
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Tag, Comment
from .forms import CommentForm, PostForm

#게시판
def post_list(request):
    posts = Post.objects.all()
    q = request.GET.get('q', '')  # 키값이 'q'로 지정된 값이 없으면 None이 반환됨
    if q:  # q가 널 아니면 qs에 filter 조건 추가
        posts = posts.filter(title__icontains=q)
    return render(request, 'post/post_list.html', {
        'post_list': posts,
        'q': q,
    })

#게시글 보여주기
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    all_tag = Tag.objects.all()
    mystr = post.tagged()
    my_tag = {}
    for t in all_tag:
        my_tag[t.name] = str(mystr).find(t.name)
    return render(request, 'post/post_detail.html',
                  {'post': post, 'my_tag': my_tag})

#게시글 작성(post_write.html로 넘어감)
def post_new(request, post=None):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            item = form.save()
            # return redirect(item)
            return redirect('post:post_list')
    else:
        form = PostForm(instance=post)

    return render(request, 'post/post_write.html', {'form': form, })

#게시글 수정
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return post_new(request, post)

#게시글 삭제
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post:post_list')

#게시글에 대한 댓글 달기(post_comment.html로 넘어감)
def post_comment(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = Post.objects.get(pk=pk)
            comment.save()
            return redirect('post:post_detail', pk)
    else:
        form = CommentForm()
    return render(request, 'post/post_comment.html', {
        'form' : form,
     })

# # 댓글 수정
# def comment_edit(request, post_pk , pk):
#     post = get_object_or_404(Post, pk=post_pk)
#     comment = get_object_or_404(Comment, pk=pk)
#
#     if request.method == 'POST':
#         form = CommentForm(request.POST, request.FILES, instance=comment)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.save()
#             return redirect('post:post_detail', post.pk)
#     else:
#         form = CommentForm(instance=comment)
#     return render(request, 'post/post_comment.html', {
#         'form' : form,
#      })

#댓글 삭제
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.id == request.POST.objects.get(username = request.user.get_username()):
        comment.delete()
        return redirect('post:post_detail')

hytrip/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>{% block title %}{% endblock %}</title>

</head>
<body>

    {% block content %}
    {% endblock content %}

    <footer>
        <p>(주)하이트립 대표 : 하수경 사업자등록번호 : 638-87-51124
        <p>고객센터 : 02-886-0000 이메일 : hytrip@gamil.com 운영시간(한국) : 11시~19시(주말/공휴일 휴무)
        <p>주소 : 서울특별시  성동구 행당동 한양여자대학교 신고 : 2018-서울관악-1368호
        <p>자사는 서울특별시관광협회 공제영업보증보험에 가입되어 있습니다. 하이트립은 통신판매중개자이며 통신판매의 당사자가 아닙니다.
        <p>따라서 하이트립은 상품·거래정보 및 거래에 대하여 책임을 지지 않습니다.
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
    {% block extra_body %}
        <script type="text/javascript" src="js/bootstrap.js"></script>
    {% endblock %} {# 자바스크립트 등을 위하여 #}
</body>
</html>

main/templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}
{# 장고에서 css, img를 사용하기 위해 사용하는 코드. prj/settings.py에서 별도의 코드 수정이 필요 #}

{% block title %}
    hytrip
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <link rel= "stylesheet" type="text/css" href="static/main/css/main_section.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<!-- jsp에서 작성한 section -->
    <div id="demo" class="carousel slide" data-ride="carousel">

      <!-- The slideshow -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="static/main/img/pic112.jpg" width="1100" height="500">
             <div class="carousel-caption">
                <h1>Enjoy your trip</h1>
                 <p>with HYtrip</p>
                 <button><i class="fa fa-map btn_map"></i>플래너 시작하기</button>
           </div>
        </div>
        <div class="carousel-item">
          <img src="static/main/img/pic42.jpg" width="1100" height="500">
             <div class="carousel-caption">
                <h1>Enjoy your trip</h1>
                 <p>We have such a good plan</p>
                 <button><i class="fa fa-map btn_map"></i>플래너 시작하기</button>
           </div>
        </div>
        <div class="carousel-item">
          <img src="static/main/img/pic22.jpg" width="1100" height="500">
             <div class="carousel-caption">
                <h1>Enjoy your trip</h1>
                 <p>please looking around our web site</p>
                 <button><i class="fa fa-map btn_map"></i>플래너 시작하기</button>
           </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>
    </div>

    <div class="wrap">
    <div class="page_title"> 최윤희님만을 위한 여행지 추천 </div>
    <div class="page_desc"> 취향에 맞는 여행지를 골라보세요! </div>
    <div class="story_list">

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/jeju.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">푸른 제주 바다</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/namu.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">건강이 좋아지는 대나무숲 길</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/han.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">한강 따라 서울구경</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/para.png" alt="" class="story_img">
          </div>
          <div class="story_title">짜릿한 추억 패러글라이딩</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>
    </div>
    </div>
    <!-- //카드 -->

     <!-- 카드 -->
    <div class="wrap">
    <div class="page_title">
                어디로 갈까?         </div>
    <div class="page_desc">
                팁에서 아이디어를 얻어보세요.         </div>
    <div class="story_list">
       <a href="#" class="story_box big">
          <div class="story_imgbox">
          <img src="static/main/img/han.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">한강 따라 서울구경</div>
          <div class="story_desc">오랜 세월의 역사와 사연을 품은 센느강의 다리들. 세계문화유산으로 지정된 다리만 10개! 아름다운 다리들과 센느강을 따라 걷기만 해도 파리의 절반은 볼 수 ...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/namu.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">건강이 좋아지는 대나무숲 길</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/jeju.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">푸른 제주 바다</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/para.png" alt="" class="story_img">
          </div>
          <div class="story_title">짜릿한 추억 패러글라이딩</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box">
          <div class="story_imgbox">
          <img src="static/main/img/ever.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">스릴 넘치는 에버랜드</div>
          <div class="story_desc">빡빡한 스케줄의 피곤한 여행은 가라. 새파란 바다와 하늘을 보며 놀고 먹...</div>
       </a>

       <a href="#" class="story_box big">
          <div class="story_imgbox">
          <img src="static/main/img/hanok.jpg" alt="" class="story_img">
          </div>
          <div class="story_title">한국의 멋 한옥마을</div>
          <div class="story_desc">오랜 세월의 역사와 사연을 품은 센느강의 다리들. 세계문화유산으로 지정된 다리만 10개! 아름다운 다리들과 센느강을 따라 걷기만 해도 파리의 절반은 볼 수 ...</div>
       </a>
    </div>
    </div>
    <!-- //카드 -->

     <div class="wrap">

     <div class="page_title"> 인기 여행지 </div>
     <div class="page_desc">
               지금 이 순간 ! 인기있는 여행지      </div>

      <div class="top_city_list">

      <div class="top_city w2">
      <div class="top_city_title"> 광화문 </div>
        <img src="static/main/img/pic1.jpg" >
      </div>

      <div class="top_city">
      <div class="top_city_title"> DDP </div>
        <img src="static/main/img/pic2.jpg" >
      </div>

      <div class="top_city">
        <img src="static/main/img/pic3.jpg" >
      </div>

       <div class="top_city">
       <div class="top_city_title"> 낙산공원 </div>
        <img src="static/main/img/pic4.jpg" >
      </div>

      <div class="top_city h2">
      <div class="top_city_title"> 롯데타워 </div>
        <img src="static/main/img/pic6.jpg" >
      </div>

      <div class="top_city">
        <img src="static/main/img/pic7.jpg" >
      </div>

      <div class="top_city">
      <div class="top_city_title"> 서울N타워 </div>
        <img src="static/main/img/pic8.jpg" >
      </div>

       <div class="top_city">
       <div class="top_city_title"> 북촌 </div>
        <img src="static/main/img/pic9.jpg" >
      </div>

       <div class="top_city">
       <div class="top_city_title"> 제주 </div>
        <img src="static/main/img/pic10.jpg" >
      </div>

       <div class="top_city">

        <img src="static/main/img/pic11.jpg" >
      </div>

      </div>
    </div>
    <!-- //jsp에서 작성한 section -->





        <!-- footer -->
  <div class="py-5 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 mb-4 mb-lg-0">
          <h5>HYtrip Web site</h5>
          <p class="text-muted">한양여자대학교 스마트IT 학과 하이트립</p>
        </div>
        <div class="col-lg-4 col-md-6">
          <h5>Boot</h5>
          <ul class="links list-unstyled">
            <li> <a href="#" class="text-muted">I like Django</a></li>
            <li> <a href="#" class="text-muted">So funny</a></li>
            <li> <a href="#" class="text-muted">Nic</a></li>
            <li> <a href="#" class="text-muted">Egoiest</a></li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6">
          <h5>Strap</h5>
          <ul class="links list-unstyled">
            <li> <a href="#" class="text-muted">Swalla</a></li>
            <li> <a href="#" class="text-muted">Nustella</a></li>
            <li> <a href="#" class="text-muted">River and rain</a></li>
            <li> <a href="#" class="text-muted">Midnight in Paris</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

maps/templates/maps/default.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>여행하고 싶을 땐 HYTRIP!</title>

    <!-- 뷰포트 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" initial-scale="1">

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />

    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.css' type='text/css' />

    <script src='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />

    <style>
        body { margin:0; padding:0; }
        .logo {
            margin: 15px;
        }
        #map {
            position:absolute;
            top:0; bottom:0;
            width:100%;
        }
        #map_navigation {
            z-index: 100;
            height: 100%;
            background-color: #dfdfdf;
            position: fixed;
            top: 0;
        }
        #map_navigation > div {
            background-color: aliceblue;
            margin: 15px;
            border : 1px solid cadetblue;
        }
        #map_navigation > div .map_btn {
            float: right;
            right: 0;
            top: 0;
        }
    </style>
</head>
<body>
    <header>
        <h1>Hytrip</h1>
{#        <nav>#}
{##}
{#        </nav>#}
    </header>

    <div id='map_navigation'>
        <h3 class="logo"><a href="main/index.html" ><img src="../static/iconfinder_airplane.svg" width="50px" /></a></h3>
{#        for 여행지 in 여행지 리스트 #}
        <div>
            <h4>서울</h4>
            <p class="map_btn"><img src="../static/plus.svg" width="30px"/></p>
            <p>한국의 수도 서울. 어쩌구 저쩌구. 어쩌저쩌구</p>
            <div><a href="#">더보기</a></div>
        </div>
        <div>
            <h4>부산</h4>
            <p class="map_btn"><img src="../static/plus.svg" width="30px"/></p>
            <p>한국의 두번째 수도 부도. 어쩌구 저쩌구. 어쩌저쩌구</p>
            <div><a href="#">더보기</a></div>
        </div>
        <div>
            <h4>세종</h4>
            <p class="map_btn"><img src="../static/plus.svg" width="30px"/></p>
            <p>요즘 뜨는 신도시, 세종. 어쩌구 저쩌구. 어쩌저쩌구</p>
            <div><a href="#">더보기</a></div>
        </div>
        <div>
            <h4>양주</h4>
            <p class="map_btn"><img src="../static/plus.svg" width="30px"/></p>
            <p>자연과 도시의 완벽한 융합. 어쩌구 저쩌구. 어쩌저쩌구</p>
            <div><a href="#">더보기</a></div>
        </div>
    </div>

    <div id='map' style='width: 100%; height: 100%;'></div>
    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoiaHl0cmlwIiwiYSI6ImNqd2Vlb2licDBsYXc0Ym8zdGhreXNmOGkifQ.xOqgdBrspMkt2RlccGx3tg';
        {#mapboxgl.accessToken = {{ mapbox_access_token }};#}
        var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/hytrip/cjwel9r761sv91cp696h89mrp',
        {#style: 'mapbox://styles/mapbox/streets-v11',#}
        center: [127, 37.52], //starting position
        zoom: 6  //starting zoom
        });

        // Add zoom and rotation controls to the map.
        map.addControl(new mapboxgl.NavigationControl());

        map.addControl(new MapboxDirections({
            accessToken: mapboxgl.accessToken
        }), 'top-right');
    </script>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
</body>
</html>

post/templates/post/post_comment.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>

    <input type="submit"/>
</form>
{% endblock content %}

post/templates/post/post_detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% block content %}
<a href="{% url 'post:post_list' %}">게시판으로 돌아가기</a>

   <form>
    <fieldset>
        id:         <input type="text" value={{ post.id }}> <br/>
        게시자:     <input type="text" value="{{ post.author }}"> <br/>
        제목:       <input type="text" value="{{ post.name }}"> <br/>
        설명:       <textarea cols="40" rows="10">{{ post.desc }}</textarea><br/>
        사진:       {% if post.photo %}<img src="{{ post.photo.url }}"/>{% endif %}<br/>
        수정 일시:  <input type="text" value="{{ post.updated }}"> <br/>
        게시 일시:  <input type="text" value="{{ post.created_at }}"> <br/>
        태그 집합:  <input type="text" value="{{ post.tagged }}"> <br/>
    </fieldset>
    </form>
<hr>
<a href="{% url 'post:post_edit' post.pk %}">게시글 수정</a>
<a href="{% url 'post:post_remove' post.pk %}">게시글 삭제</a>
<br/>
<hr>
<a href="{% url 'post:post_comment' post.pk %}">댓글쓰기</a>
<br/>
<table>
        <thead>
            <th>id</th>
            <th>댓글</th>
            <th>작성 일시</th>
            <th>수정 일시</th>
            <th>delete</th>
        </thead>
        <tbody>
        <hr>
        {% for c in post.comments.all %}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ c.message }}</td>
                <small>
                <td>{{ c.created_at }}</td>
                <td>{{ c.updated }}</td>
                <td><a href="{% url 'post:comment_remove' post.pk %}">삭제</a></td>
                </small>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock content %}

post/templates/post/post_list.html
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
<link rel="stylesheet" href="static/css/bootstrap.css">
<!-- 게시판 테이블 생성(겉에 구조 잡아주는 역할) -->
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>번호</th>
            <th>이름</th>
            <th>설명</th>
            <th>사진</th>
            <th>등록 일시</th>
            <th>태그 집합</th>
            <th>조회수</th>
            <th>수정</th>
            <th>삭제</th>
        </tr>
        </thead>
        <tbody>
        <!-- 게시판 테이블 생성(안에 들어가는 내용물) -->
        {% if post_list %}
            {% for post in post_list %}
        <tr>
                <td> {{ post.id }} </td>
                <td>
                <a href="/post/{{ post.pk }}"></a>
                <a href="{{ post.get_absolute_url }}">{{ post.name }}</a>
                </td>
                <td> {{ post.desc }} </td>
                <td> {{ post.photo }} </td>
                <td> {{ post.created_at }} </td>
                <td> {{ post.tagged }} </td>
                <td> {{ post.update_counter }} </td>
                <td>
                    <a href="{% url 'post:post_edit' post.pk %}">수정</a>
                </td>
                <td>
                    <a href="{% url 'post:post_remove' post.pk %}">삭제</a>
                </td>
        </tr>
        {% endfor %}
        {% else %}
        <p>There are no posts in the board</p>
        {% endif %}
        </tbody>
        </table>
        <!-- 글쓰기 페이지로 넘어가는 링크 -->
        <a  href="{% url 'post:post_new' %}" class="btn btn-default pull-right"> 글쓰기</a>

    </div>
{% endblock content%}
<script src="js/jquery-3.1.1.js"></script>
<script src="js/bootstrap.js"></script>